# Generated by Django 5.1.4 on 2024-12-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
                ('categoria', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=11, max_digits=13)),
                ('longitud', models.DecimalField(decimal_places=11, max_digits=13)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
